# Generated by Django 2.0.5 on 2018-06-03 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20180602_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hash',
            field=models.CharField(default=38264307669403278229398196540852439611, max_length=128, unique=True, verbose_name='Hash'),
        ),
    ]
