# Generated by Django 2.0.5 on 2018-05-30 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributeforitemlist',
            name='type',
            field=models.CharField(choices=[('STARS', 'Stars'), ('SCORES_5', 'Scores 0 to 5'), ('SCORES_10', 'Scores 0 to 10'), ('SCORES_100', 'Scores 0 to 100'), ('INT_VALUE', 'Integer Value'), ('FLOAT_VALUES', 'Float Value')], max_length=50, verbose_name='Title'),
        ),
    ]
