# Generated by Django 2.0.5 on 2018-05-23 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180523_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hash',
            field=models.CharField(default=255887330239291311899986015766274620946, max_length=128, unique=True, verbose_name='Hash'),
        ),
    ]
