# Generated by Django 2.0.5 on 2018-06-02 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20180529_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hash',
            field=models.CharField(default=248846863550096692956441608145730185178, max_length=128, unique=True, verbose_name='Hash'),
        ),
    ]
