# Generated by Django 2.0.5 on 2018-06-02 21:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('lists', '0002_auto_20180529_2154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attributeforitemlist',
            name='list',
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['created_at']},
        ),
        migrations.RemoveField(
            model_name='item',
            name='description',
        ),
        migrations.RemoveField(
            model_name='item',
            name='status',
        ),
        migrations.RemoveField(
            model_name='item',
            name='title',
        ),
        migrations.AddField(
            model_name='item',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Product', verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='item',
            name='quantity',
            field=models.FloatField(default=0, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='item',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lists.List', verbose_name='List'),
        ),
        migrations.AlterField(
            model_name='list',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lists', to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
        migrations.AlterUniqueTogether(
            name='list',
            unique_together=set(),
        ),
        migrations.DeleteModel(
            name='AttributeForItemList',
        ),
        migrations.RemoveField(
            model_name='list',
            name='type',
        ),
    ]
